<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access token' => '',
    'Admin Panel Module' => '',
    'Auth key' => '',
    'Avatar' => '',
    'Check your email for further instructions.' => '',
    'Created at' => '',
    'Email' => '',
    'Follow the link below to reset your password:
{link}' => '',
    'Hello {username}' => '',
    'I forgot my password' => '',
    'I remembered my old password!' => '',
    'I remembered my password!' => '',
    'ID' => '',
    'Last visit at' => '',
    'New password was saved.' => '',
    'Password' => '',
    'Password hash' => '',
    'Password reset for {app}' => '',
    'Password reset token' => '',
    'Please choose your new password:' => '',
    'Please fill out your email. A link to reset password will be sent there.' => '',
    'Real name' => '',
    'Remember me' => '',
    'Request password reset' => '',
    'Reset password' => '',
    'Role' => '',
    'Save' => '',
    'Search' => '',
    'Send' => '',
    'Sign in' => '',
    'Sign me in' => '',
    'Sorry, we are unable to reset password for email provided.' => '',
    'Status' => '',
    'This email is already registered.' => '',
    'This username is already registered.' => '',
    'Updated at' => '',
    'Username' => '',
];
