<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access token' => 'Код доступа',
    'ID' => '',
    'New password' => 'Новый пароль',
    'Password reset token' => 'Код для сброса пароля',
    'Password reset token cannot be blank.' => 'Не задан код для сброса пароля.',
    'Verification code' => 'Проверочный код',
    'Wrong password reset token.' => 'Неверный код для сброса пароля',
    'Admin Panel Module' => 'Модуль панели администратора',
    'Auth key' => 'Ключ авторизации',
    'Avatar' => 'Аватар',
    'Check your email for further instructions.' => 'Проверьте свою почту для дальнейших инструкций.',
    'Created at' => 'Создан в',
    'Email' => 'Email',
    'Follow the link below to reset your password:
{link}' => 'Для смены пароля проследуйте по ссылке:
{link}',
    'Hello {username}' => 'Здравствуйте, {username}',
    'I forgot my password' => 'Я забыл пароль',
    'I remembered my old password!' => 'Я вспомнил старый пароль!',
    'I remembered my password!' => 'Я вспомнил свой пароль!',
    'Last visit at' => 'Последнее посещение в',
    'New password was saved.' => 'Новый пароль сохранен.',
    'Password' => 'Пароль',
    'Password hash' => 'Хеш пароля',
    'Password reset for {app}' => 'Сброс пароля для {app}',
    'Please choose your new password:' => 'Выберите новый пароль:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Напишите адрес своей электронной почты. Мы вышлем на него ссылку для сброса пароля.',
    'Real name' => 'Настоящее имя',
    'Remember me' => 'Запомнить меня',
    'Request password reset' => 'Запрос сброса пароля',
    'Reset password' => 'Сбросить пароль',
    'Role' => 'Роль',
    'Save' => 'Сохранить',
    'Search' => 'Найти',
    'Send' => 'Отправить',
    'Sign in' => 'Вход',
    'Sign me in' => 'Войти',
    'Sorry, we are unable to reset password for email provided.' => 'Извините, но мы не можем сбросить пароль для данного адреса.',
    'Status' => 'Статус',
    'This email is already registered.' => 'Такой email уже зарегистирован.',
    'This username is already registered.' => 'Такое имя пользователя уже зарегистрировано.',
    'Updated at' => 'Обновлен в',
    'Username' => 'Имя пользователя',
];
