<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'An internal server error occurred.' => 'Внутренняя ошибка сервера.',
  'Back to dashboard' => 'На главную',
  'Back to index' => 'На главную',
  'Bad file.' => 'Плохой файл.',
  'Brand logo file' => 'Логотип бренда',
  'Brand name' => 'Название бренда',
  'Browse server' => 'Посмотреть на сервере',
  'Configuration' => 'Настройки',
  'Configuration was saved successfully.' => 'Настройки успешно сохранены.',
  'Couldn\'t save configuration file.' => 'Не удалось сохранить файл настроек.',
  'Dashboard' => 'Главная',
  'Description' => 'Описание',
  'Drop Image Here…' => 'Претащите и бросьте файл сюда',
  'Error' => 'Ошибка',
  'File manager' => 'Файловый менеджер',
  'Help text' => 'Текст помощи',
  'Home' => 'Домой',
  'ID' => '',
  'Installed modules' => 'Установленные модули',
  'Log Out' => 'Выйти',
  'Module configuration' => 'Настройки модуля',
  'Module name' => 'Имя модуля',
  'Module not found.' => 'Модуль не найден.',
  'Modules' => 'Модули',
  'Modules Configuration' => 'Настроки модулей',
  'Modules not found.' => 'Модулей не найдено.',
  'New' => 'Новый',
  'No configuration' => 'Нет настроек',
  'No file' => 'Нет файла',
  'Profile' => 'Профиль',
  'Remove' => 'Удалить',
  'Replace…' => 'Изменить...',
  'Reset' => 'Сбрость',
  'Return back' => 'Назад',
  'Routes' => 'Маршруты',
  'Save' => 'Сохранить',
  'Set URL' => 'Ввести адрес',
  'Settings' => 'Настройки',
  'Settings not found.' => 'Настройки не найдены',
  'Sort in admin menu' => 'Сортировка в меню администратора (число)',
  'To site' => 'На сайт',
  'Toggle Dropdown' => 'Показать список',
  'Toggle navigation' => 'Показать навигацию',
  'Upload files' => 'Загрузка файлов',
  'Uploads directory' => 'Папка для загрузки файлов',
  'Upload…' => 'Загрузить...',
  'Version' => 'Версия',
  'View uploaded files' => 'Просмотр загруженных файлов',
  'Window title in admin panel' => 'Заголовок окна в панели администратора',
  '_module_description_' => 'Отображает панель администратора. Управляет модулями и их конфигурацией.',
  '_module_name_' => 'Панель администратора',
);
