<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'An internal server error occurred.' => '',
  'Back to dashboard' => '',
  'Back to index' => '',
  'Bad file.' => '',
  'Brand logo file' => '',
  'Brand name' => '',
  'Browse server' => '',
  'Change' => '@@@@',
  'Change site settings' => '@@@@',
  'Configuration' => '',
  'Configuration was saved successfully.' => '',
  'Couldn\'t save configuration file.' => '',
  'Dashboard' => '',
  'Description' => '',
  'Drop Image Here…' => '',
  'Error' => '',
  'File manager' => '',
  'Help text' => '',
  'Home' => '',
  'ID' => '',
  'Installed modules' => '',
  'Log Out' => '',
  'Module configuration' => '',
  'Module name' => '',
  'Module not found.' => '',
  'Modules' => '',
  'Modules Configuration' => '',
  'Modules not found.' => '',
  'New' => '',
  'No configuration' => '',
  'No file' => '',
  'Profile' => '',
  'Remove' => '',
  'Replace…' => '',
  'Reset' => '',
  'Return back' => '',
  'Routes' => '',
  'Save' => '',
  'Select file' => '@@@@',
  'Select image' => '@@@@',
  'Set URL' => '',
  'Settings' => '',
  'Settings not found.' => '',
  'To site' => '',
  'Toggle Dropdown' => '',
  'Toggle navigation' => '',
  'Upload files' => '',
  'Uploads directory' => '',
  'Upload…' => '',
  'Version' => '',
  'View uploaded files' => '',
  'Window title in admin panel' => '',
  '_module_description_' => 'Provides control over your modules, configurations and other.',
  '_module_name_' => 'Admin panel',
);
